import { defineConfig, env } from '@nexus/service-kit';
export const config = defineConfig({
  nodeEnv: env('string', { default: 'development' }),
  port: env('number', { default: 4009 }),
  databaseUrl: env('string', { required: true, secret: true }),
  cookieSecret: env('string', { required: true, secret: true }),
  serviceToken: env('string', { required: true, secret: true }),
  tokenIssuer: env('string', { default: 'http://localhost:4001' }),
  jwksUrl: env('string', { default: 'http://localhost:4001/.well-known/jwks.json' }),
  identityUrl: env('string', { default: 'http://localhost:4001' }),
  gatewayUrl: env('string', { default: 'http://localhost:4000' }),
  tenancyUrl: env('string', { default: 'http://localhost:4002' }),
  aiApiKey: env('string', { secret: true }),
  aiProvider: env('string', { default: 'nvidia' }),
  nvidiaApiKey: env('string', { secret: true }),
  nvidiaApiUrl: env('string'),
  anthropicApiKey: env('string', { secret: true }),
  anthropicApiUrl: env('string', { default: 'https://api.anthropic.com/v1/messages' }),
  supportAiModel: env('string'),
  aiBaseUrl: env('string'),
  aiModel: env('string'),
  mcpAllowedHosts: env('list', { default: ['localhost', '127.0.0.1', '[::1]'] }),
  mcpAllowedOrigins: env('list', { default: ['http://localhost:3100', 'http://localhost:3000'] }),
});
